WebAutopark/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WebAutopark.BusinessLayer.Interfaces;
using WebAutopark.BusinessLayer.Models;
using WebAutopark.Core.Constants;
using WebAutopark.Core.Entities.Identity;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    [Route("orders")]
    public class OrderController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper;

        public OrderController(IOrderService orderService, IMapper mapper, ICartService cartService,
            UserManager<User> userManager)
        {
            _orderService = orderService;
            _mapper = mapper;
            _cartService = cartService;
            _userManager = userManager;
        }

        [HttpGet("index/")]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            const int adminId = 1;
            var user = await _userManager.FindByNameAsync(User.Identity?.Name);
            var userId = int.Parse(await _userManager.GetUserIdAsync(user));

            var orders = await _orderService.GetAll();
            var mappedOrders = _mapper.Map<IEnumerable<OrderViewModel>>(orders);

            if (userId == adminId)
            {
                return View(mappedOrders);
            }

            var userOrders = mappedOrders.Where(o => o.UserId == userId);

            return View(userOrders);
        }

        [HttpGet("create/")]
        [Authorize]
        public async Task<IActionResult> OrderCreate(int userId)
        {
            var cartItemModels = await _cartService.GetAll();
            var cartItemViewModels = _mapper.Map<List<ShoppingCartItemViewModel>>(cartItemModels);

            var orderViewModel = new OrderViewModel
            {
                CartItems = cartItemViewModels,
                UserId = userId,
                TotalPrice = _cartService.GetTotalPrice(cartItemModels)
            };

            return View(orderViewModel);
        }

        [HttpPost("create/")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OrderCreate(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                var orderModel = _mapper.Map<OrderModel>(orderViewModel);
                await _cartService.SetCartItemsAndTotalPrice(orderModel);
                
                await _orderService.Create(orderModel);

                return RedirectToAction("Index");
            }

            var model = new OrderViewModel
            {
                CartItems = _mapper.Map<List<ShoppingCartItemViewModel>>(await _cartService.GetAll())
            };

            return View(model);
        }

        [HttpGet("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> OrderUpdate(int id)
        {
            var updateModel = await _orderService.GetById(id);

            if (updateModel is null)
                return NotFound();

            return View(_mapper.Map<OrderViewModel>(updateModel));
        }
        
        [HttpPost("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OrderUpdate(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                await _orderService.Update(_mapper.Map<OrderModel>(orderViewModel));

                return RedirectToAction("Index");
            }

            return View(orderViewModel);
        }

        [HttpGet("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ActionName("OrderDelete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var deleteModel = await _orderService.GetById(id);

            if (deleteModel is null)
                return NotFound();

            return View(_mapper.Map<OrderViewModel>(deleteModel));
        }

        [HttpPost("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> OrderDelete(int id)
        {
            await _orderService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAutopark.BusinessLayer.Interfaces;
using WebAutopark.BusinessLayer.Models;
using WebAutopark.Core.Constants;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    [Route("products")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public ProductController(IProductService productService, IMapper mapper)
        {
            _productService = productService;
            _mapper = mapper;
        }

        [HttpGet("index/")]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var models = await _productService.GetAll();

            return View(_mapper.Map<List<ProductViewModel>>(models));
        }

        [HttpGet("info/")]
        [Authorize]
        public async Task<IActionResult> ProductInfo(int id)
        {
            var model = await _productService.GetById(id);

            return View(_mapper.Map<ProductViewModel>(model));
        }
        
        [HttpGet("create/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public IActionResult ProductCreate()
        {
            return View();
        }
        
        [HttpPost("create/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProductCreate(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                await _productService.Create(_mapper.Map<ProductModel>(productViewModel));
                return RedirectToAction("Index");
            }

            return View();
        }
        
        [HttpGet("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> ProductUpdate(int id)
        {
            var updatedModel = await _productService.GetById(id);

            if (updatedModel is null)
                return NotFound();

            return View(_mapper.Map<ProductViewModel>(updatedModel));
        }

        [HttpPost("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ProductUpdate(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                await _productService.Update(_mapper.Map<ProductModel>(productViewModel));
                return RedirectToAction("Index");
            }

            return View(productViewModel);
        }

        [HttpGet("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ActionName("ProductDelete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var deleteModel = await _productService.GetById(id);

            if (deleteModel is null)
                return NotFound();

            return View(_mapper.Map<ProductViewModel>(deleteModel));
        }

        [HttpPost("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> ProductDelete(int id)
        {
            await _productService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebAutopark.Core.Constants;
using WebAutopark.Core.Entities.Identity;

namespace WebAutopark.Controllers
{
    [Route("users")]
    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UserController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet("index/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            
            return View(users);
        }
        
        [HttpGet("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ActionName("UserDelete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var deletedModel = await _userManager.Users.SingleAsync(u => u.Id == id);

            if (deletedModel is null)
                return NotFound();

            return View(deletedModel);
        }
        
        [HttpPost("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> UserDelete(int id)
        {
            var user = await _userManager.Users.SingleAsync(u => u.Id == id);
            
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Controllers/VehicleTypeController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using WebAutopark.BusinessLayer.Interfaces;
using WebAutopark.BusinessLayer.Models;
using WebAutopark.Core.Constants;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    [Route("vehicleTypes/")]
    public class VehicleTypeController : Controller
    {
        private readonly IVehicleTypeService _vehicleTypeService;
        private readonly IMapper _mapper;

        public VehicleTypeController(IVehicleTypeService vehicleTypeService, IMapper mapper)
        {
            _vehicleTypeService = vehicleTypeService;
            _mapper = mapper;
        }

        [HttpGet("index/")]
        public async Task<IActionResult> Index()
        {
            var models = await _vehicleTypeService.GetAll();

            return View(_mapper.Map<IEnumerable<VehicleTypeViewModel>>(models));
        }

        [HttpGet("info/")]
        public async Task<IActionResult> VehicleTypeInfo(int id)
        {
            var model = await _vehicleTypeService.GetById(id);

            if (model is null)
                return NotFound();

            return View(_mapper.Map<VehicleTypeViewModel>(model));
        }

        [HttpGet("create/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public IActionResult VehicleTypeCreate()
        {
            return View();
        }

        [HttpPost("create/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VehicleTypeCreate(VehicleTypeViewModel vehicleType)
        {
            if (ModelState.IsValid)
            {
                await _vehicleTypeService.Create(_mapper.Map<VehicleTypeModel>(vehicleType));
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> VehicleTypeUpdate(int id)
        {
            var updatedModel = await _vehicleTypeService.GetById(id);

            if (updatedModel is null)
                return NotFound();

            return View(_mapper.Map<VehicleTypeViewModel>(updatedModel));
        }

        [HttpPost("/update")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VehicleTypeUpdate(VehicleTypeViewModel vehicleType)
        {
            if (ModelState.IsValid)
            {
                await _vehicleTypeService.Update(_mapper.Map<VehicleTypeModel>(vehicleType));
                return RedirectToAction("Index");
            }

            return View(vehicleType);
        }

        [HttpGet("/delete")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ActionName("VehicleTypeDelete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var deletedModel = await _vehicleTypeService.GetById(id);

            if (deletedModel is null)
                return NotFound();

            return View(_mapper.Map<VehicleTypeViewModel>(deletedModel));
        }

        [HttpPost("/delete")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> VehicleTypeDelete(int id)
        {
            await _vehicleTypeService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder marginTop1" >
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" >
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

WebAutopark/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container text-center">
        <a href="https://docs.microsoft.com/en-us/">Link to Microsoft Documentation</a>
    </div>
</footer>

WebAutopark/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using WebAutopark.Core.Entities.Identity

@inject UserManager<User> _userManager

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAutopark</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-route-userId="@_userManager.GetUserId(User)" asp-controller="Order" asp-action="Index">Order</a>
                        </li>
                        @if(User.IsInRole("admin") )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="VehicleType" asp-action="Index">VehicleType</a>
                            </li>
                        }
                    }
                </ul>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li>
                            <span class="navbar-text text-dark">@User.Identity.Name</span>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-action="logout" asp-controller="account">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link text-dark" asp-action="register" asp-controller="account">Register</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-action="login" asp-controller="account">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

WebAutopark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebAutopark</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/style.css"/>
</head>
<body>
    <partial name="_Header"></partial>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <partial name="_Footer"></partial>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true" type="module"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

WebAutopark/Views/Shared/_ProductSummary.cshtml
@model WebAutopark.Models.ProductViewModel

<div class="card col-md-4 col-sm-4">
    <div class="card-header">
        <img src="@Model.ImgUrl" alt="img/productViewModel-2.jpg" class="card-img" style="object-fit: contain" height="300">
    </div>
    
    <div class="card-body">
        @if (Model.Name.Length > 35)
        {
            <h2 class="">@(Model.Name[..32])...</h2>
        }
        else
        {
            <h2 class="">@Model.Name</h2>
        }
        <p class="">@Model.Description</p>
        
        <div class="d-flex justify-content-between">
            <ins class="">@Model.Price $</ins>
            
            @if (User.Identity!.IsAuthenticated)
            {
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddProduct" asp-route-id="@Model.Id">Add</a>
            }
        </div>
        <hr>
        @if (User.IsInRole("admin"))
        {
            <div class="d-flex justify-content-between">
                <a class="btn btn-secondary" asp-controller="Product" asp-action="ProductUpdate" asp-route-id="@Model.Id">Update</a>
                <a class="btn btn-danger" asp-controller="Product" asp-action="ProductDelete" asp-route-id="@Model.Id">Delete</a>
            </div>
        }
    </div>
</div>