WebAutopark/Models/ShoppingCartViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace WebAutopark.Models
{
    public class ShoppingCartViewModel
    {
        public List<ShoppingCartItemViewModel> ShoppingCarts { get; set; }

        public decimal TotalPrice => ShoppingCarts.Sum(product => product.Product.Price * product.Amount);
    }
}

WebAutopark/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using WebAutopark.BusinessLayer.Interfaces;
using WebAutopark.BusinessLayer.Models;
using WebAutopark.Core.Constants;
using WebAutopark.Core.Entities.Identity;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    [Route("orders")]
    public class OrderController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;
        private readonly IMapper _mapper;

        public OrderController(IOrderService orderService, IMapper mapper, ICartService cartService,
            UserManager<User> userManager)
        {
            _orderService = orderService;
            _mapper = mapper;
            _cartService = cartService;
            _userManager = userManager;
        }

        [HttpGet("index/")]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            const int adminId = 1;
            var user = await _userManager.FindByNameAsync(User.Identity?.Name);
            var userId = int.Parse(await _userManager.GetUserIdAsync(user));

            var orders = await _orderService.GetAll();
            var mappedOrders = _mapper.Map<IEnumerable<OrderViewModel>>(orders);

            if (userId == adminId)
            {
                return View(mappedOrders);
            }

            var userOrders = mappedOrders.Where(o => o.UserId == userId);

            return View(userOrders);
        }

        [HttpGet("create/")]
        [Authorize]
        public async Task<IActionResult> OrderCreate(int userId)
        {
            var cartItemModels = await _cartService.GetAll();
            var cartItemViewModels = _mapper.Map<List<ShoppingCartItemViewModel>>(cartItemModels);

            var orderViewModel = new OrderViewModel
            {
                CartItems = cartItemViewModels,
                UserId = userId,
                TotalPrice = _cartService.GetTotalPrice(cartItemModels)
            };

            return View(orderViewModel);
        }

        [HttpPost("create/")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OrderCreate(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                var orderModel = _mapper.Map<OrderModel>(orderViewModel);
                await _cartService.SetCartItemsAndTotalPrice(orderModel);
                
                await _orderService.Create(orderModel);

                return RedirectToAction("Index");
            }

            var model = new OrderViewModel
            {
                CartItems = _mapper.Map<List<ShoppingCartItemViewModel>>(await _cartService.GetAll())
            };

            return View(model);
        }

        [HttpGet("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> OrderUpdate(int id)
        {
            var updateModel = await _orderService.GetById(id);

            if (updateModel is null)
                return NotFound();

            return View(_mapper.Map<OrderViewModel>(updateModel));
        }
        
        [HttpPost("update/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> OrderUpdate(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                await _orderService.Update(_mapper.Map<OrderModel>(orderViewModel));

                return RedirectToAction("Index");
            }

            return View(orderViewModel);
        }

        [HttpGet("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        [ActionName("OrderDelete")]
        public async Task<IActionResult> ConfirmDelete(int id)
        {
            var deleteModel = await _orderService.GetById(id);

            if (deleteModel is null)
                return NotFound();

            return View(_mapper.Map<OrderViewModel>(deleteModel));
        }

        [HttpPost("delete/")]
        [Authorize(Roles = IdentityRoleConstant.Admin)]
        public async Task<IActionResult> OrderDelete(int id)
        {
            await _orderService.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Controllers/ShoppingCartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAutopark.BusinessLayer.Interfaces;
using WebAutopark.Models;

namespace WebAutopark.Controllers
{
    [Route("carts")]
    public class ShoppingCartController : Controller
    {
        private readonly ICartService _shoppingCartService;
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public ShoppingCartController(ICartService shoppingCartService, IProductService productService, IMapper mapper)
        {
            _shoppingCartService = shoppingCartService;
            _productService = productService;
            _mapper = mapper;
        }

        [HttpGet("index/")]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var models = await _shoppingCartService.GetAll();
            
            var mappedModels = _mapper.Map<List<ShoppingCartItemViewModel>>(models);
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCarts = mappedModels
            };

            return View(shoppingCartViewModel);
        }

        [Route("add/")]
        [Authorize]
        public async Task<IActionResult> AddProduct(int id)
        {
            var product = await _productService.GetAll();
            var selectedProduct = product.FirstOrDefault(p => p.Id == id);

            if (selectedProduct != null)
            {
                await _shoppingCartService.AddProduct(selectedProduct, 1);
            }
            
            return RedirectToAction("Index");
        }
        
        [Route("remove/")]
        [Authorize]
        public async Task<IActionResult> RemoveProduct(int id)
        {
            var product = await _productService.GetAll();
            var selectedProduct = product.FirstOrDefault(p => p.Id == id);

            if (selectedProduct != null)
            {
                await _shoppingCartService.RemoveProduct(selectedProduct);
            }
            
            return RedirectToAction("Index");
        }
        
        [Route("clear/")]
        [Authorize]
        public async Task<IActionResult> ClearCart()
        {
            await _shoppingCartService.ClearCart();

            return RedirectToAction("Index");
        }
    }
}

WebAutopark/Views/ShoppingCart/Index.cshtml
@using WebAutopark.Core.Entities.Identity
@using Microsoft.AspNetCore.Identity
@model ShoppingCartViewModel
@inject UserManager<User> _userManager

@{
    ViewData["Title"] = "CartList";
}

<div class="card col-md-7 m-auto">
    <div class="card-header d-flex justify-content-between">
        <h2 class="">Cart</h2>
        <a class="btn btn-outline-dark" style="padding: 1.5% 2.5%;" asp-controller="Home" asp-action="Index">&times;</a>
    </div>
    <form class="card-body" method="post" asp-controller="Order" asp-action="OrderCreate">
        @if (Model!.ShoppingCarts.Count != 0)
        {
            <table class="table table-bordered table-striped">
                <thead class="thead-light">
                <tr>
                    <th class="" width="20%">Name</th>
                    <th class="" width="20%">TotalPrice</th>
                    <th class="" width="20%">Amount</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var cart in Model.ShoppingCarts)
                {
                    <tr>
                        <td>@cart.Product.Name</td>
                        <td>@cart.Product.Price $</td>
                        <td>@cart.Amount</td>
                        <td class="text-center" style="width: 0%">
                            <a class="delete_productViewModel_button" asp-controller="ShoppingCart" asp-action="RemoveProduct" asp-route-id="@cart.Product.Id">Delete</a>
                        </td>
                    </tr>
                }
                </tbody>
                <tfoot>
                <tr>
                    <td>Total price:</td>
                    <td colspan="3" class="text-center">@Model.TotalPrice $</td>
                </tr>
                </tfoot>
            </table>
            <div class="d-flex justify-content-between">                
                <a type="submit" class="btn btn-danger" asp-controller="ShoppingCart" asp-action="ClearCart">Discard</a>
                <a type="submit" class="btn btn-primary" asp-controller="Order" asp-action="OrderCreate" asp-route-userId="@_userManager.GetUserId(User)">Create Order</a>
            </div>
        }
        else
        {
            <div>
                <p>Your cart is empty. You have not added any productViewModels.</p>
            </div>
        }
    </form>
</div>